"""Seed endpoint — serves the complete system rules catalog as JSON.

This is the single source of truth for the frontend: effects, extras, flaws,
conditions, attributes, skills, advantages, equipment, base features.
All data extracted from CodigoHeroi_v2-2.md.
"""

from fastapi import APIRouter

router = APIRouter(prefix="/api/system", tags=["system"])


# ────────────────────────────────────────────────────────────
# ATTRIBUTES
# ────────────────────────────────────────────────────────────
ATTRIBUTES = [
    {"key": "FOR", "name": "Força", "description": "Potência muscular e aplicação física", "uses": "Dano melee, carga, arremessos, Atletismo"},
    {"key": "RES", "name": "Resistência", "description": "Saúde, vitalidade, recuperação", "uses": "Vitalidade máxima, resistência a toxinas, Fortitude"},
    {"key": "AGI", "name": "Agilidade", "description": "Velocidade, equilíbrio, coordenação", "uses": "Esquiva, Iniciativa, Acrobacia, Furtividade"},
    {"key": "DES", "name": "Destreza", "description": "Precisão, mira, controle fino", "uses": "Ataque distância, Furto, Pilotagem, Fabricação"},
    {"key": "CMB", "name": "Combate", "description": "Instinto e técnica corpo a corpo", "uses": "Ataque melee, Parry, manobras de combate"},
    {"key": "INT", "name": "Intelecto", "description": "Raciocínio, memória, capacidade analítica", "uses": "Tecnologia, Investigação, Expertise, Tratamento"},
    {"key": "PER", "name": "Percepção", "description": "Intuição, sentidos, leitura de situação", "uses": "Percepção ativa, Insight, Resistência mental"},
    {"key": "PRE", "name": "Presença", "description": "Carisma, autoridade, personalidade", "uses": "Persuasão, Intimidação, Decepção, Liderança"},
]

ATTR_COST_TABLE = [
    {"rank": 1, "description": "Deficiente", "pp_cumulative": -1},
    {"rank": 2, "description": "Humano médio (gratuito)", "pp_cumulative": 0},
    {"rank": 3, "description": "Treinado/acima da média", "pp_cumulative": 2},
    {"rank": 4, "description": "Excepcional — pico humano", "pp_cumulative": 4},
    {"rank": 5, "description": "Sobre-humano baixo", "pp_cumulative": 8},
    {"rank": 6, "description": "Sobre-humano alto", "pp_cumulative": 14},
]

# ────────────────────────────────────────────────────────────
# SKILLS
# ────────────────────────────────────────────────────────────
SKILLS = [
    {"name": "Acrobacia", "attribute": "AGI", "untrained": False, "description": "Equilíbrio, manobras, quedas controladas, parkour"},
    {"name": "Atletismo", "attribute": "FOR", "untrained": True, "description": "Escalada, natação, corrida, salto, força bruta"},
    {"name": "Combate Melee", "attribute": "CMB", "untrained": True, "description": "Bônus de ataque melee específico (tipo)", "has_specialization": True},
    {"name": "Combate Distância", "attribute": "DES", "untrained": True, "description": "Bônus de ataque à distância específico (tipo)", "has_specialization": True},
    {"name": "Decepção", "attribute": "PRE", "untrained": True, "description": "Mentir, blefar, disfarce, manipulação social"},
    {"name": "Expertise", "attribute": "INT", "untrained": False, "description": "Conhecimento técnico em área nomeada", "has_specialization": True},
    {"name": "Furtividade", "attribute": "AGI", "untrained": True, "description": "Mover-se sem ser detectado, vigilância discreta"},
    {"name": "Insight", "attribute": "PER", "untrained": True, "description": "Ler intenções, detectar mentiras, análise comportamental"},
    {"name": "Intimidação", "attribute": "PRE", "untrained": True, "description": "Ameaçar, pressão psicológica, desmoralizar"},
    {"name": "Investigação", "attribute": "INT", "untrained": False, "description": "Analisar cenas, coletar evidências, pesquisa"},
    {"name": "Liderança", "attribute": "PRE", "untrained": True, "description": "Comandar, inspirar, coordenar sob pressão"},
    {"name": "Percepção", "attribute": "PER", "untrained": True, "description": "Detecção sensorial ativa: notar detalhes, perigos"},
    {"name": "Persuasão", "attribute": "PRE", "untrained": True, "description": "Convencer sinceramente, negociar, diplomacia"},
    {"name": "Pilotagem", "attribute": "DES", "untrained": False, "description": "Manobrar veículo em condições adversas", "has_specialization": True},
    {"name": "Tecnologia", "attribute": "INT", "untrained": False, "description": "Operar, reparar, criar, hackear dispositivos"},
    {"name": "Tratamento", "attribute": "INT", "untrained": False, "description": "Primeiros socorros, medicina, remover condições"},
]

# ────────────────────────────────────────────────────────────
# POWER EFFECTS
# ────────────────────────────────────────────────────────────
EFFECTS = [
    # ── Attack ──
    {"name": "Affliction", "name_pt": "Aflição", "category": "attack", "base_cost": 1, "cost_type": "per_dp",
     "action": "standard", "range": "close", "duration": "instant", "resistance": "RES_or_PER",
     "exclusive_extras": ["Concentration", "Cumulative", "Extra Condition", "Progressive"],
     "exclusive_flaws": ["Instant Recovery", "Limited Degree"],
     "ui_type": "condition_picker",
     "description": "Impõe condições progressivas ao alvo (3 graus)"},
    {"name": "Blast", "name_pt": "Rajada", "category": "attack", "base_cost": 2, "cost_type": "per_dp",
     "action": "standard", "range": "ranged", "duration": "instant", "resistance": "vitalidade",
     "exclusive_extras": ["Multiattack", "Accurate"], "exclusive_flaws": [],
     "ui_type": "default", "description": "Ataque à distância versátil"},
    {"name": "Damage", "name_pt": "Dano", "category": "attack", "base_cost": 1, "cost_type": "per_dp",
     "action": "standard", "range": "close", "duration": "instant", "resistance": "vitalidade",
     "exclusive_extras": ["Strength-based", "Penetrating"], "exclusive_flaws": [],
     "ui_type": "default", "description": "Ataque corpo a corpo direto"},
    {"name": "Dazzle", "name_pt": "Ofuscar", "category": "attack", "base_cost": 2, "cost_type": "per_dp",
     "action": "standard", "range": "ranged", "duration": "instant", "resistance": "RES_or_PER",
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "sense_selector", "description": "Ataca um sentido específico do alvo"},
    {"name": "Energy Aura", "name_pt": "Aura de Energia", "category": "attack", "base_cost": 4, "cost_type": "per_dp",
     "action": "reaction", "range": "close", "duration": "instant", "resistance": "vitalidade",
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Dano automático a quem toca o usuário"},
    {"name": "Nullify", "name_pt": "Nulificar", "category": "attack", "base_cost": 1, "cost_type": "per_dp",
     "action": "standard", "range": "ranged", "duration": "instant", "resistance": "opposed_dp",
     "exclusive_extras": ["Broad", "Simultaneous", "Concentration"], "exclusive_flaws": [],
     "ui_type": "descriptor_selector", "description": "Suprime efeitos de um descritor específico"},
    {"name": "Sleep", "name_pt": "Sono", "category": "attack", "base_cost": 2, "cost_type": "per_dp",
     "action": "standard", "range": "ranged", "duration": "instant", "resistance": "RES",
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Progressão: Fatigado → Exausto → Adormecido"},
    {"name": "Snare", "name_pt": "Enredar", "category": "attack", "base_cost": 3, "cost_type": "per_dp",
     "action": "standard", "range": "ranged", "duration": "instant", "resistance": "AGI",
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Contenção física/energética progressiva"},
    {"name": "Suffocation", "name_pt": "Sufocação", "category": "attack", "base_cost": 4, "cost_type": "per_dp",
     "action": "standard", "range": "ranged", "duration": "instant", "resistance": "RES",
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Priva o alvo de ar"},
    {"name": "Weaken", "name_pt": "Enfraquecer", "category": "attack", "base_cost": 1, "cost_type": "per_dp",
     "action": "standard", "range": "close", "duration": "instant", "resistance": "RES_or_PER",
     "exclusive_extras": ["Broad", "Simultaneous"], "exclusive_flaws": [],
     "ui_type": "stat_selector", "description": "Reduz temporariamente atributo/habilidade/defesa"},

    # ── Defense ──
    {"name": "Deflect", "name_pt": "Deflexão", "category": "defense", "base_cost": 1, "cost_type": "per_dp",
     "action": "standard", "range": "ranged", "duration": "instant", "resistance": None,
     "exclusive_extras": ["Reaction"], "exclusive_flaws": [],
     "ui_type": "default", "description": "Intercede ataques à distância"},
    {"name": "Force Field", "name_pt": "Campo de Força", "category": "defense", "base_cost": 1, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": ["Affects Others"], "exclusive_flaws": [],
     "ui_type": "default", "description": "Adiciona defesa/Vitalidade enquanto sustentado"},
    {"name": "Immortality", "name_pt": "Imortalidade", "category": "defense", "base_cost": 2, "cost_type": "per_dp",
     "action": "none", "range": "personal", "duration": "permanent", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "rank_display", "description": "Revive após morte (tempo depende do rank)"},
    {"name": "Immunity", "name_pt": "Imunidade", "category": "defense", "base_cost": 1, "cost_type": "flat_variable",
     "action": "none", "range": "personal", "duration": "permanent", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "immunity_picker", "description": "Resistência total a efeitos específicos"},
    {"name": "Protection", "name_pt": "Proteção", "category": "defense", "base_cost": 1, "cost_type": "per_dp",
     "action": "none", "range": "personal", "duration": "permanent", "resistance": None,
     "exclusive_extras": ["Impervious"], "exclusive_flaws": [],
     "ui_type": "impervious_toggle", "description": "Adiciona dP à Vitalidade máxima permanentemente"},
    {"name": "Regeneration", "name_pt": "Regeneração", "category": "defense", "base_cost": 1, "cost_type": "per_dp",
     "action": "none", "range": "personal", "duration": "permanent", "resistance": None,
     "exclusive_extras": ["Persistent"], "exclusive_flaws": [],
     "ui_type": "rank_display", "description": "Remove Ferimentos automaticamente ao longo do tempo"},

    # ── Control ──
    {"name": "Create", "name_pt": "Criação", "category": "control", "base_cost": 2, "cost_type": "per_dp",
     "action": "standard", "range": "ranged", "duration": "sustained", "resistance": None,
     "exclusive_extras": ["Continuous", "Movable", "Stationary"], "exclusive_flaws": [],
     "ui_type": "default", "description": "Cria objetos/estruturas a partir do nada"},
    {"name": "Duplication", "name_pt": "Duplicação", "category": "control", "base_cost": 3, "cost_type": "per_dp",
     "action": "standard", "range": "close", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "budget_calc", "description": "Cria cópias com dP×15 PP cada"},
    {"name": "Element Control", "name_pt": "Controle de Elemento", "category": "control", "base_cost": 2, "cost_type": "per_dp",
     "action": "standard", "range": "perception", "duration": "sustained", "resistance": "FOR",
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "element_selector", "description": "Controla elemento/substância específica"},
    {"name": "Environment", "name_pt": "Ambiente", "category": "control", "base_cost": 1, "cost_type": "per_dp_variable",
     "action": "standard", "range": "rank", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "environment_config", "description": "Altera condições ambientais da área"},
    {"name": "Illusion", "name_pt": "Ilusão", "category": "control", "base_cost": 1, "cost_type": "per_dp_variable",
     "action": "standard", "range": "perception", "duration": "sustained", "resistance": "PER",
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "sense_multi_selector", "description": "Cria percepções falsas (custo por nº de sentidos)"},
    {"name": "Luck Control", "name_pt": "Controle de Sorte", "category": "control", "base_cost": 3, "cost_type": "per_dp",
     "action": "reaction", "range": "perception", "duration": "instant", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "mode_selector", "description": "Manipula probabilidade e Hero Dice"},
    {"name": "Mind Control", "name_pt": "Controle Mental", "category": "control", "base_cost": 4, "cost_type": "per_dp",
     "action": "standard", "range": "perception", "duration": "instant", "resistance": "PER",
     "exclusive_extras": [], "exclusive_flaws": ["Sense-Dependent", "Limited"],
     "ui_type": "default", "description": "Dazed → Compelled → Controlled"},
    {"name": "Mind Reading", "name_pt": "Leitura Mental", "category": "control", "base_cost": 2, "cost_type": "per_dp",
     "action": "standard", "range": "perception", "duration": "sustained", "resistance": "PER",
     "exclusive_extras": ["Cumulative", "Sensory Link"], "exclusive_flaws": [],
     "ui_type": "margin_display", "description": "Lê pensamentos (profundidade = margem)"},
    {"name": "Move Object", "name_pt": "Telecinese", "category": "control", "base_cost": 2, "cost_type": "per_dp",
     "action": "standard", "range": "ranged", "duration": "sustained", "resistance": "FOR",
     "exclusive_extras": ["Damaging", "Perception Range", "Precise"], "exclusive_flaws": [],
     "ui_type": "default", "description": "Move objetos/criaturas à distância"},
    {"name": "Summon", "name_pt": "Invocar", "category": "control", "base_cost": 2, "cost_type": "per_dp",
     "action": "standard", "range": "close", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "budget_calc", "description": "Invoca entidade com dP×15 PP"},
    {"name": "Transform", "name_pt": "Transformar", "category": "control", "base_cost": 2, "cost_type": "per_dp_variable",
     "action": "standard", "range": "close", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "tier_picker", "description": "Converte materiais (custo 2-5 PP/dP por amplitude)"},

    # ── Movement ──
    {"name": "Burrowing", "name_pt": "Escavar", "category": "movement", "base_cost": 1, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Movimento através de terra/pedra/sólidos"},
    {"name": "Flight", "name_pt": "Voo", "category": "movement", "base_cost": 2, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": ["Gliding", "Winged"],
     "ui_type": "default", "description": "Movimento aéreo"},
    {"name": "Leaping", "name_pt": "Salto", "category": "movement", "base_cost": 1, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "instant", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Distância de salto = rank na Escala de Medida"},
    {"name": "Speed", "name_pt": "Velocidade", "category": "movement", "base_cost": 1, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Movimento terrestre acelerado"},
    {"name": "Swimming", "name_pt": "Natação", "category": "movement", "base_cost": 1, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Movimento aquático sem penalidade"},
    {"name": "Teleport", "name_pt": "Teletransporte", "category": "movement", "base_cost": 2, "cost_type": "per_dp",
     "action": "move", "range": "rank", "duration": "instant", "resistance": None,
     "exclusive_extras": ["Accurate", "Extended", "Portal"],
     "exclusive_flaws": ["Medium", "Turnabout"],
     "ui_type": "teleport_config", "description": "Movimento instantâneo"},
    {"name": "Movement", "name_pt": "Movimento Especial", "category": "movement", "base_cost": 2, "cost_type": "per_rank",
     "action": "varies", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "mode_multi_select", "description": "Cada rank = 1 modo especial de movimento"},

    # ── Sensory ──
    {"name": "Communication", "name_pt": "Comunicação", "category": "sensory", "base_cost": 4, "cost_type": "per_dp",
     "action": "free", "range": "rank", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "medium_selector", "description": "Comunicação à distância via meio específico"},
    {"name": "Comprehend", "name_pt": "Compreensão", "category": "sensory", "base_cost": 2, "cost_type": "per_dp",
     "action": "none", "range": "personal", "duration": "permanent", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "option_multi_select", "description": "Cada dP = uma opção de compreensão"},
    {"name": "Concealment", "name_pt": "Ocultação", "category": "sensory", "base_cost": 2, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": ["Attack"], "exclusive_flaws": [],
     "ui_type": "sense_multi_selector", "description": "Esconde o personagem de um ou mais sentidos"},
    {"name": "Remote Sensing", "name_pt": "Sentidos Remotos", "category": "sensory", "base_cost": 1, "cost_type": "per_dp_variable",
     "action": "free", "range": "rank", "duration": "sustained", "resistance": None,
     "exclusive_extras": ["Simultaneous"], "exclusive_flaws": [],
     "ui_type": "sense_multi_selector", "description": "Desloca sentidos para local distante (custo por nº de sentidos)"},
    {"name": "Senses", "name_pt": "Sentidos Ampliados", "category": "sensory", "base_cost": 1, "cost_type": "per_rank",
     "action": "none", "range": "personal", "duration": "permanent", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "senses_mega_picker", "description": "Cada rank = 1 melhoria sensorial"},

    # ── General ──
    {"name": "Alternate Form", "name_pt": "Forma Alternativa", "category": "general", "base_cost": 0, "cost_type": "component_sum",
     "action": "move", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": ["Activation"],
     "ui_type": "form_builder", "description": "Forma alternativa completa (soma dos componentes)"},
    {"name": "Elongation", "name_pt": "Alongamento", "category": "general", "base_cost": 1, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Cada dP = +1.5m de alcance melee"},
    {"name": "Enhanced Trait", "name_pt": "Atributo Aprimorado", "category": "general", "base_cost": 0, "cost_type": "trait_cost",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "trait_selector", "description": "Ranks adicionais sustentados em atributo/habilidade/defesa"},
    {"name": "Extra Limbs", "name_pt": "Membros Extras", "category": "general", "base_cost": 1, "cost_type": "per_dp",
     "action": "none", "range": "personal", "duration": "permanent", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Cada rank = +1 ação livre de manipulação/round"},
    {"name": "Feature", "name_pt": "Característica", "category": "general", "base_cost": 1, "cost_type": "per_rank",
     "action": "none", "range": "personal", "duration": "permanent", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "freeform", "description": "Capacidade menor narrativa (1 PP/rank)"},
    {"name": "Growth", "name_pt": "Crescimento", "category": "general", "base_cost": 2, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "growth_preview", "description": "A cada 2 ranks: +1 FOR, +1 massa, −1 defesas ativas, +1 Vitalidade"},
    {"name": "Healing", "name_pt": "Cura", "category": "general", "base_cost": 2, "cost_type": "per_dp",
     "action": "standard", "range": "close", "duration": "instant", "resistance": None,
     "exclusive_extras": ["Persistent", "Restorative", "Resurrection", "Self"],
     "exclusive_flaws": [],
     "ui_type": "healing_config", "description": "Restaura Vitalidade e remove Ferimentos"},
    {"name": "Insubstantial", "name_pt": "Insubstancialidade", "category": "general", "base_cost": 5, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": ["Affects Corporeal"], "exclusive_flaws": [],
     "ui_type": "form_rank_selector", "description": "4 formas: Fluido, Gasoso, Energético, Fantasmático"},
    {"name": "Mimic", "name_pt": "Mímico", "category": "general", "base_cost": 8, "cost_type": "per_dp",
     "action": "move", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "budget_calc", "description": "Copia traits de alvo percebido (dP×15 PP)"},
    {"name": "Morph", "name_pt": "Morfologia", "category": "general", "base_cost": 5, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": ["Metamorph"], "exclusive_flaws": [],
     "ui_type": "rank_display", "description": "Muda aparência (flexibilidade por rank)"},
    {"name": "Quickness", "name_pt": "Rapidez", "category": "general", "base_cost": 1, "cost_type": "per_dp",
     "action": "free", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "default", "description": "Tarefas rotineiras ×10 mais rápido por rank"},
    {"name": "Variable", "name_pt": "Variável", "category": "general", "base_cost": 7, "cost_type": "per_dp",
     "action": "standard", "range": "personal", "duration": "sustained", "resistance": None,
     "exclusive_extras": [], "exclusive_flaws": [],
     "ui_type": "variable_allocator", "description": "dP×5 PP alocáveis em qualquer efeito do descritor"},
]

# ────────────────────────────────────────────────────────────
# EXTRAS (universal)
# ────────────────────────────────────────────────────────────
EXTRAS = [
    {"name": "Accurate", "cost_type": "flat_per_rank", "cost": 1, "description": "+2d ao pool de ataque por rank"},
    {"name": "Affects Corporeal", "cost_type": "flat_per_rank", "cost": 1, "description": "Insubstancial pode afetar o mundo físico"},
    {"name": "Affects Insubstantial", "cost_type": "flat", "cost": 1, "description": "Funciona contra insubstanciais (+1=metade, +2=total)", "max_ranks": 2},
    {"name": "Affects Objects", "cost_type": "per_dp", "cost": 1, "description": "Efeitos RES/PER podem atingir objetos inanimados"},
    {"name": "Affects Others", "cost_type": "per_dp", "cost": 1, "description": "Efeito pessoal pode ser concedido a outro (toque + Standard)"},
    {"name": "Affects Self", "cost_type": "per_dp", "cost": 0, "description": "Efeito que afeta apenas outros pode afetar o usuário também"},
    {"name": "Alternate Effect (static)", "cost_type": "flat", "cost": 1, "description": "Efeito alternativo no array; apenas 1 ativo por vez"},
    {"name": "Alternate Effect (dynamic)", "cost_type": "flat", "cost": 2, "description": "Alternativo dinâmico — pode compartilhar dP com outros dinâmicos"},
    {"name": "Alternate Resistance", "cost_type": "per_dp", "cost": 1, "description": "Muda a resistência padrão do efeito"},
    {"name": "Area (Burst)", "cost_type": "per_dp", "cost": 1, "description": "Esfera de 9m de raio a partir do ponto de impacto"},
    {"name": "Area (Cloud)", "cost_type": "per_dp", "cost": 1, "description": "Nuvem de 4.5m que persiste 1 round após duração"},
    {"name": "Area (Cone)", "cost_type": "per_dp", "cost": 1, "description": "Cone de 18m a partir do usuário"},
    {"name": "Area (Cylinder)", "cost_type": "per_dp", "cost": 1, "description": "Cilindro de 9m raio × 9m altura"},
    {"name": "Area (Line)", "cost_type": "per_dp", "cost": 1, "description": "Linha de 1.5m largura × 9m comprimento"},
    {"name": "Area (Perception)", "cost_type": "per_dp", "cost": 1, "description": "Afeta todos que percebem o ponto alvo"},
    {"name": "Area (Shapeable)", "cost_type": "per_dp", "cost": 1, "description": "9m³ de volume, forma contígua livre"},
    {"name": "Attack", "cost_type": "per_dp", "cost": 0, "description": "Converte efeito pessoal em ataque"},
    {"name": "Contagious", "cost_type": "per_dp", "cost": 1, "description": "Se espalha via contato com alvo afetado"},
    {"name": "Cumulative", "cost_type": "per_dp", "cost": 1, "description": "Graus de efeito acumulam entre ataques sucessivos"},
    {"name": "Dimensional", "cost_type": "flat", "cost": 1, "description": "1=uma dimensão; 2=grupo; 3=qualquer", "max_ranks": 3},
    {"name": "Extended Range", "cost_type": "flat_per_rank", "cost": 1, "description": "Dobra todas as faixas de alcance por rank"},
    {"name": "Feature", "cost_type": "flat_per_rank", "cost": 1, "description": "Capacidade menor integrada ao efeito (narrativa)"},
    {"name": "Homing", "cost_type": "flat_per_rank", "cost": 1, "description": "Se errar: re-tentativa automática no próximo turno (1 por rank)"},
    {"name": "Impervious", "cost_type": "per_dp", "cost": 1, "description": "Defesa ignora ataques com Dano Líquido ≤ metade do rank"},
    {"name": "Increased Duration", "cost_type": "per_dp", "cost": 1, "description": "Sobe tier de duração: Instant→Conc→Sustained→Continuous"},
    {"name": "Increased Mass", "cost_type": "flat_per_rank", "cost": 1, "description": "+1 rank de massa carregável/afetável por rank"},
    {"name": "Increased Range", "cost_type": "per_dp", "cost": 1, "description": "Sobe alcance: Close→Ranged→Perception"},
    {"name": "Incurable", "cost_type": "flat", "cost": 1, "description": "Cura e Regeneração não revertem os efeitos deste poder"},
    {"name": "Indirect", "cost_type": "flat", "cost": 1, "description": "Origem/direção alterada (+1 a +4 flat conforme nível)", "max_ranks": 4},
    {"name": "Innate", "cost_type": "flat", "cost": 1, "description": "Não pode ser Nulificado — parte da natureza intrínseca"},
    {"name": "Insidious", "cost_type": "flat", "cost": 1, "description": "Alvo pode não saber que foi afetado (TN4 para detectar)"},
    {"name": "Linked", "cost_type": "flat", "cost": 0, "description": "Dois efeitos sempre juntos; custo somado; 1 rolagem de ataque"},
    {"name": "Multiattack", "cost_type": "per_dp", "cost": 1, "description": "Pode atingir múltiplos alvos ou mesmo alvo várias vezes"},
    {"name": "Penetrating", "cost_type": "flat_per_rank", "cost": 1, "description": "Ignora dP de Protection Impervious até o rank"},
    {"name": "Perception Range", "cost_type": "per_dp", "cost": 1, "description": "Qualquer alvo percebido; sem rolagem de ataque"},
    {"name": "Persistent", "cost_type": "per_dp", "cost": 1, "description": "Efeito age mesmo em dano 'Incurável'"},
    {"name": "Precise", "cost_type": "flat", "cost": 1, "description": "Pode executar tarefas de detalhe fino com o efeito"},
    {"name": "Ranged", "cost_type": "per_dp", "cost": 1, "description": "Converte efeito Close em Ranged"},
    {"name": "Rapid", "cost_type": "per_dp", "cost": 1, "description": "Comunica/percebe ×10 mais rápido por rank"},
    {"name": "Reach", "cost_type": "flat_per_rank", "cost": 1, "description": "Estende alcance melee +1.5m por rank"},
    {"name": "Reaction", "cost_type": "per_dp", "cost": 3, "description": "Converte Standard→Reaction (+1 se Free→Reaction)"},
    {"name": "Resurrection", "cost_type": "flat_per_rank", "cost": 1, "description": "Pode recuperar mortos dentro de (dP) horas"},
    {"name": "Reversible", "cost_type": "flat", "cost": 1, "description": "Pode voluntariamente desfazer como ação Livre"},
    {"name": "Ricochet", "cost_type": "flat_per_rank", "cost": 1, "description": "Pode redirecionar por até X superfícies por rank"},
    {"name": "Secondary Effect", "cost_type": "per_dp", "cost": 1, "description": "Efeito instantâneo age duas vezes (2ª no próximo round)"},
    {"name": "Selective", "cost_type": "per_dp", "cost": 1, "description": "Área exclui alvos escolhidos pelo usuário"},
    {"name": "Sensory Link", "cost_type": "per_dp", "cost": 1, "description": "Percebe via sentidos do alvo enquanto conectado"},
    {"name": "Sleep", "cost_type": "per_dp", "cost": 0, "description": "Incapacitado se torna adormecido em vez de inconsciente"},
    {"name": "Split", "cost_type": "flat_per_rank", "cost": 1, "description": "Divide efeito em múltiplos alvos menores por rank"},
    {"name": "Strength-based", "cost_type": "per_dp", "cost": 0, "description": "Adiciona FOR ao pool de ataque (Damage)"},
    {"name": "Subtle", "cost_type": "flat", "cost": 1, "description": "1=TN4 pra detectar; 2=indetectável por sentidos normais", "max_ranks": 2},
    {"name": "Sustained", "cost_type": "per_dp", "cost": 0, "description": "Converte Permanent em Sustained (pode ligar/desligar)"},
    {"name": "Triggered", "cost_type": "flat_per_rank", "cost": 1, "description": "Define condição de auto-ativação; X usos pré-configurados"},
    {"name": "Variable Descriptor", "cost_type": "flat", "cost": 1, "description": "1=descritores relacionados; 2=qualquer descritor", "max_ranks": 2},
]

# ────────────────────────────────────────────────────────────
# FLAWS (universal)
# ────────────────────────────────────────────────────────────
FLAWS = [
    {"name": "Activation", "cost_type": "flat", "discount": 1, "description": "−1: ativar requer Move; −2: requer Standard", "max_ranks": 2},
    {"name": "Check Required", "cost_type": "per_dp", "discount": 1, "description": "Rolagem de habilidade obrigatória para usar (TN=10+rank)"},
    {"name": "Close Range", "cost_type": "per_dp", "discount": 1, "description": "Converte Ranged em Close (somente toque)"},
    {"name": "Concentration", "cost_type": "per_dp", "discount": 1, "description": "Sustained agora requer Standard por turno para manter"},
    {"name": "Diminished Range", "cost_type": "flat_per_rank", "discount": 1, "description": "Reduz faixas de alcance ÷2 por rank (máx 3)"},
    {"name": "Distracting", "cost_type": "per_dp", "discount": 1, "description": "Usar torna o usuário Vulnerável até início do próximo turno"},
    {"name": "Fades", "cost_type": "per_dp", "discount": 1, "description": "Perde 1 dP de eficácia por uso; para em 0; recarrega fora de combate"},
    {"name": "Feedback", "cost_type": "per_dp", "discount": 1, "description": "Manifestações atacadas causam dano proporcional ao usuário"},
    {"name": "Full Power", "cost_type": "flat", "discount": 1, "description": "Só utilizável no rank máximo; ranks parciais impossíveis"},
    {"name": "Grab-Based", "cost_type": "per_dp", "discount": 1, "description": "Requer Grab bem-sucedido; efeito dispara como reação automática"},
    {"name": "Inaccurate", "cost_type": "flat_per_rank", "discount": 1, "description": "−2d no pool de ataque por rank"},
    {"name": "Increased Action", "cost_type": "per_dp", "discount": 1, "description": "Aumenta ação requerida: Free→Move, Move→Std, etc."},
    {"name": "Limited (Descriptor)", "cost_type": "per_dp", "discount": 1, "description": "Não funciona contra/sem descritor específico"},
    {"name": "Limited (Situation)", "cost_type": "per_dp", "discount": 1, "description": "Funciona em ~metade das situações"},
    {"name": "Noticeable", "cost_type": "flat", "discount": 1, "description": "Efeito contínuo/permanente tem manifestação perceptível"},
    {"name": "Permanent", "cost_type": "per_dp", "discount": 1, "description": "Efeito contínuo se torna permanente — não pode ser desativado"},
    {"name": "Quirk", "cost_type": "flat_per_rank", "discount": 1, "description": "Pequena desvantagem específica (máx 2 PP valor total)"},
    {"name": "Reduced Range", "cost_type": "per_dp", "discount": 1, "description": "Reduz alcance: Perception→Ranged=−1; Ranged→Close=−1"},
    {"name": "Removable", "cost_type": "per_5pp", "discount": 1, "description": "No objeto: removível apenas quando stunned+defenseless"},
    {"name": "Easily Removable", "cost_type": "per_5pp", "discount": 2, "description": "No objeto: removível com Disarm ou Grab em combate"},
    {"name": "Resistible", "cost_type": "per_dp", "discount": 1, "description": "Efeito sem resistência agora tem uma"},
    {"name": "Sense-Dependent", "cost_type": "per_dp", "discount": 1, "description": "Alvo deve perceber o efeito; pode bloquear sentido para resistir"},
    {"name": "Side Effect (failure)", "cost_type": "per_dp", "discount": 1, "description": "Falhar causa efeito negativo no usuário"},
    {"name": "Side Effect (always)", "cost_type": "per_dp", "discount": 2, "description": "Cada uso: efeito negativo independente do sucesso"},
    {"name": "Tiring", "cost_type": "per_dp", "discount": 1, "description": "Usar causa 1 nível de Fadiga"},
    {"name": "Uncontrolled", "cost_type": "per_dp", "discount": 1, "description": "GM controla quando e como o efeito funciona"},
    {"name": "Unreliable (roll)", "cost_type": "per_dp", "discount": 1, "description": "Role d10 antes de usar: 1-5=falha neste turno"},
    {"name": "Unreliable (uses)", "cost_type": "per_dp", "discount": 1, "description": "Funciona por (dP) usos fixos; depois: sem efeito até recarregar"},
    {"name": "Gliding", "cost_type": "per_dp", "discount": 1, "description": "Apenas planar em descida; sem subida (exclusivo Flight)"},
    {"name": "Winged", "cost_type": "per_dp", "discount": 1, "description": "Requer espaço físico para asas; inútil em espaços confinados (exclusivo Flight)"},
    {"name": "Instant Recovery", "cost_type": "per_dp", "discount": 1, "description": "Recuperação automática sem rolagem ao fim da duração (exclusivo Affliction)"},
    {"name": "Limited Degree", "cost_type": "per_dp", "discount": 1, "description": "Máximo 2 graus de efeito (exclusivo Affliction)"},
    {"name": "Medium", "cost_type": "per_dp", "discount": 1, "description": "Requer superfície/substância específica como ponto de entrada/saída (exclusivo Teleport)"},
    {"name": "Turnabout", "cost_type": "per_dp", "discount": 1, "description": "Ao teleportar, outro objeto/pessoa troca de lugar (exclusivo Teleport)"},
]

# ────────────────────────────────────────────────────────────
# CONDITIONS
# ────────────────────────────────────────────────────────────
CONDITIONS = [
    {"name": "Compelled", "name_pt": "Compelido", "severity": 2, "effect": "Apenas 1 ação específica/turno (definida pelo efeito)"},
    {"name": "Controlled", "name_pt": "Controlado", "severity": 3, "effect": "Age conforme controlador; sem ações próprias"},
    {"name": "Dazed", "name_pt": "Atordoado", "severity": 1, "effect": "Perde 1d de qualquer pool neste turno"},
    {"name": "Deaf", "name_pt": "Surdo", "severity": 1, "effect": "−2d em pools dependentes de audição; pode ser surpreendido"},
    {"name": "Defenseless", "name_pt": "Indefeso", "severity": 2, "effect": "Pool de defesa = 0; melee ganham +2d automático"},
    {"name": "Disabled", "name_pt": "Incapaz", "severity": 2, "effect": "1 ação (Principal OU Movimento) por turno"},
    {"name": "Entranced", "name_pt": "Fascinado", "severity": 1, "effect": "Apenas movimento; interrompido por ameaça ou dano"},
    {"name": "Exhausted", "name_pt": "Exausto", "severity": 2, "effect": "−2d TODOS os pools; Impaired simultâneo"},
    {"name": "Fatigued", "name_pt": "Fatigado", "severity": 1, "effect": "−1d TODOS os pools; Fatigado de novo = Exausto"},
    {"name": "Hindered", "name_pt": "Lento", "severity": 1, "effect": "Velocidade de movimento reduzida pela metade"},
    {"name": "Immobile", "name_pt": "Imóvel", "severity": 2, "effect": "Velocidade = 0; pool de Dodge = 0"},
    {"name": "Impaired", "name_pt": "Prejudicado", "severity": 1, "effect": "−2d em pools de Combate e Habilidades ativas"},
    {"name": "Incapacitated", "name_pt": "Incapacitado", "severity": 3, "effect": "Não pode agir; pool de defesa = 0; Ferimento se atacado"},
    {"name": "Mortal", "name_pt": "Mortal", "severity": 3, "effect": "−4d TODOS os pools; 1 ação/turno; próximo dano = Morte"},
    {"name": "Dying", "name_pt": "Morrendo", "severity": 3, "effect": "Inconsciente; RES TN2 por round ou +1 Ferimento"},
    {"name": "Paralyzed", "name_pt": "Paralisado", "severity": 3, "effect": "Pool de defesa = 0; sem ação física; consciente/percebe"},
    {"name": "Prone", "name_pt": "Derrubado", "severity": 1, "effect": "−2d melee; adjacentes +2d vs. você; +2d sua defesa ranged"},
    {"name": "Restrained", "name_pt": "Preso", "severity": 2, "effect": "Imóvel + Vulnerável simultâneos"},
    {"name": "Staggered", "name_pt": "Cambaleante", "severity": 1, "effect": "−1d pools; 1 ação/turno; de novo = Incapacitado"},
    {"name": "Stunned", "name_pt": "Estunado", "severity": 2, "effect": "Ação e pool de defesa = 0 por 1 turno completo"},
    {"name": "Transformed", "name_pt": "Transformado", "severity": 3, "effect": "Stats e forma conforme especificações do efeito"},
    {"name": "Unaware", "name_pt": "Inconsciente de tudo", "severity": 3, "effect": "Não percebe o ambiente; Indefeso vs. TODOS"},
    {"name": "Vulnerable", "name_pt": "Vulnerável", "severity": 1, "effect": "−2d pool de defesa (apenas Parry e Dodge)"},
    {"name": "Asleep", "name_pt": "Adormecido", "severity": 3, "effect": "Inconsciente; despertado por ataque ou agitação"},
]

# ────────────────────────────────────────────────────────────
# ADVANTAGES
# ────────────────────────────────────────────────────────────
ADVANTAGES = [
    # Combat
    {"name": "Accurate Attack", "category": "combat", "ranked": False, "cost": 1, "description": "Troca dP de poder por dados de ataque (máx ±5d)"},
    {"name": "All-out Attack", "category": "combat", "ranked": False, "cost": 1, "description": "Troca dados de defesa por dados de ataque (máx ±5d)"},
    {"name": "Chokehold", "category": "combat", "ranked": False, "cost": 1, "description": "Enquanto mantém Grab: alvo começa a sufocar"},
    {"name": "Close Attack", "category": "combat", "ranked": True, "cost": 1, "description": "+1d em todos os ataques melee por rank"},
    {"name": "Defensive Attack", "category": "combat", "ranked": False, "cost": 1, "description": "Troca dados de ataque por dados de defesa (máx ±5d)"},
    {"name": "Defensive Roll", "category": "combat", "ranked": True, "cost": 1, "description": "+1 Vitalidade por rank (sustentado)"},
    {"name": "Evasion", "category": "combat", "ranked": True, "cost": 1, "description": "Rank 1: TN −1 em área; Rank 2: sem dano se resistir com AGI", "max_ranks": 2},
    {"name": "Favored Environment", "category": "combat", "ranked": False, "cost": 1, "description": "+1d ataque OU defesa em ambiente escolhido"},
    {"name": "Grabbing Finesse", "category": "combat", "ranked": False, "cost": 1, "description": "Usa DES em vez de FOR para Grab; não fica Vulnerável"},
    {"name": "Improved Aim", "category": "combat", "ranked": False, "cost": 1, "description": "Ao mirar: +2d próximo ataque close, +1d ranged"},
    {"name": "Improved Critical", "category": "combat", "ranked": True, "cost": 1, "description": "Rank 1: 10=3 suc; Rank 2+: 9-10=2 suc cada"},
    {"name": "Improved Defense", "category": "combat", "ranked": False, "cost": 1, "description": "+1d defesa ao usar ação Defender"},
    {"name": "Improved Disarm", "category": "combat", "ranked": False, "cost": 1, "description": "Sem penalidade em Disarm; alvo não contra-ataca"},
    {"name": "Improved Grab", "category": "combat", "ranked": False, "cost": 1, "description": "Grab com 1 mão, outra livre; não fica Vulnerável"},
    {"name": "Improved Hold", "category": "combat", "ranked": False, "cost": 1, "description": "−1d no pool de escape do alvo agarrado"},
    {"name": "Improved Initiative", "category": "combat", "ranked": True, "cost": 1, "description": "+2 posições de Iniciativa por rank"},
    {"name": "Improved Smash", "category": "combat", "ranked": False, "cost": 1, "description": "Sem penalidade ao atingir objeto segurado por outro"},
    {"name": "Improved Trip", "category": "combat", "ranked": False, "cost": 1, "description": "Sem penalidade em Trip; alvo não contra-ataca"},
    {"name": "Improvised Weapon", "category": "combat", "ranked": True, "cost": 1, "description": "Usa Combate Melee com arma improvisada; +1dP dano/rank"},
    {"name": "Move-by Action", "category": "combat", "ranked": False, "cost": 1, "description": "Move antes E depois da ação principal"},
    {"name": "Power Attack", "category": "combat", "ranked": False, "cost": 1, "description": "−1d ataque por +1dP dano (máx ±5)"},
    {"name": "Precise Attack", "category": "combat", "ranked": True, "cost": 1, "description": "Ignora penalidades de cobertura/ocultação por rank", "max_ranks": 4},
    {"name": "Prone Fighting", "category": "combat", "ranked": False, "cost": 1, "description": "Sem penalidade quando Derrubado"},
    {"name": "Quick Draw", "category": "combat", "ranked": False, "cost": 1, "description": "Sacar arma como ação Livre"},
    {"name": "Ranged Attack", "category": "combat", "ranked": True, "cost": 1, "description": "+1d em todos os ataques ranged por rank"},
    {"name": "Redirect", "category": "combat", "ranked": False, "cost": 1, "description": "Após feint bem-sucedido: redireciona ataque falho para adjacente"},
    {"name": "Set-up", "category": "combat", "ranked": True, "cost": 1, "description": "Transfere benefício de feint para 1 aliado por rank"},
    {"name": "Takedown", "category": "combat", "ranked": True, "cost": 1, "description": "Incapacitar minion dá ataque grátis ao adjacente; Rank 2: qualquer alvo", "max_ranks": 2},
    {"name": "Throwing Mastery", "category": "combat", "ranked": True, "cost": 1, "description": "+1dP dano em arremessos por rank"},
    {"name": "Uncanny Dodge", "category": "combat", "ranked": False, "cost": 1, "description": "Não fica Vulnerável quando surpreendido"},
    {"name": "Weapon Bind", "category": "combat", "ranked": False, "cost": 1, "description": "Após defesa vs arma: Disarm reativo como ação Livre"},
    {"name": "Weapon Break", "category": "combat", "ranked": False, "cost": 1, "description": "Após defesa vs arma: ataque à arma como ação Livre"},
    # Fortune
    {"name": "Beginner's Luck", "category": "fortune", "ranked": False, "cost": 1, "description": "Gasta 1 HD: usa qualquer habilidade como rank 3 nesta cena"},
    {"name": "Inspire", "category": "fortune", "ranked": True, "cost": 1, "description": "1×/cena, gasta 1 HD: aliados ganham +1d/rank em todas as rolagens até seu próximo turno", "max_ranks": 5},
    {"name": "Leadership", "category": "fortune", "ranked": False, "cost": 1, "description": "Standard + 1 HD: remove Dazed, Fatigued ou Stunned de aliado próximo"},
    {"name": "Luck", "category": "fortune", "ranked": True, "cost": 1, "description": "X vezes/sessão: adiciona 1d10 ao pool após ver resultado"},
    {"name": "Seize Initiative", "category": "fortune", "ranked": False, "cost": 1, "description": "Gasta 1 HD no início do combate: age primeiro"},
    {"name": "Ultimate Effort", "category": "fortune", "ranked": False, "cost": 1, "description": "Gasta 1 HD: rola pool duas vezes e soma sucessos de ambas"},
    # General
    {"name": "Animal Empathy", "category": "general", "ranked": False, "cost": 1, "description": "Usa habilidades de interação com animais sem penalidade"},
    {"name": "Assessment", "category": "general", "ranked": False, "cost": 1, "description": "Insight TN2: descobre tamanho do pool de defesa do oponente"},
    {"name": "Attractive", "category": "general", "ranked": True, "cost": 1, "description": "+1d/rank em interação social com partes atraídas", "max_ranks": 2},
    {"name": "Benefit", "category": "general", "ranked": True, "cost": 1, "description": "Benefício narrativo permanente: riqueza, status, imunidade diplomática..."},
    {"name": "Connected", "category": "general", "ranked": False, "cost": 1, "description": "Persuasão para solicitar favores de rede de contatos"},
    {"name": "Contacts", "category": "general", "ranked": False, "cost": 1, "description": "Investigação para obter informações via contatos"},
    {"name": "Daze", "category": "general", "ranked": True, "cost": 1, "description": "Rank 1: Decepção; Rank 2: Intimidação — Standard para Daze alvo inteligente", "max_ranks": 2},
    {"name": "Diehard", "category": "general", "ranked": False, "cost": 1, "description": "Estabiliza automaticamente em estado Mortal sem rolagem"},
    {"name": "Eidetic Memory", "category": "general", "ranked": False, "cost": 1, "description": "Memória perfeita; INT para detalhes obscuros"},
    {"name": "Equipment", "category": "general", "ranked": True, "cost": 1, "description": "5 pontos de equipamento por rank"},
    {"name": "Extraordinary Effort", "category": "general", "ranked": False, "cost": 1, "description": "Extra Effort concede 2 benefícios em vez de 1"},
    {"name": "Fearless", "category": "general", "ranked": False, "cost": 1, "description": "Imune a todos os efeitos baseados em medo"},
    {"name": "Great Endurance", "category": "general", "ranked": False, "cost": 1, "description": "+2d resistindo fadiga, calor/frio extremo, afogamento"},
    {"name": "Hide in Plain Sight", "category": "general", "ranked": False, "cost": 1, "description": "Esconde-se sem precisar de Decepção/Intimidação"},
    {"name": "Instant Up", "category": "general", "ranked": False, "cost": 1, "description": "Levantar-se de Prone como ação Livre"},
    {"name": "Interpose", "category": "general", "ranked": False, "cost": 1, "description": "1×/round: interpõe-se entre ataque e aliado"},
    {"name": "Inventor", "category": "general", "ranked": False, "cost": 1, "description": "Usa Tecnologia para criar dispositivos/invenções"},
    {"name": "Jack-of-All-Trades", "category": "general", "ranked": False, "cost": 1, "description": "Usa qualquer habilidade sem treinamento"},
    {"name": "Languages", "category": "general", "ranked": True, "cost": 1, "description": "Rank 1: +1 idioma; cada rank dobra"},
    {"name": "Minion", "category": "general", "ranked": True, "cost": 1, "description": "NPC aliado com (rank×15) PP"},
    {"name": "Ritualist", "category": "general", "ranked": False, "cost": 1, "description": "Usa Expertise para criar/executar rituais"},
    {"name": "Second Chance", "category": "general", "ranked": True, "cost": 1, "description": "Para 1 perigo específico: re-rola e usa melhor resultado"},
    {"name": "Sidekick", "category": "general", "ranked": True, "cost": 1, "description": "NPC aliado com (rank×5) PP; mais autônomo que Minion"},
    {"name": "Skill Mastery", "category": "general", "ranked": False, "cost": 1, "description": "Habilidade específica: sucesso automático em TN 2 sob pressão"},
    {"name": "Teamwork", "category": "general", "ranked": False, "cost": 1, "description": "+1d em rolagens cooperativas quando aliado também tem"},
    {"name": "Trance", "category": "general", "ranked": False, "cost": 1, "description": "Meditação (1 min): soma PER à duração de apneia"},
    {"name": "Well-Informed", "category": "general", "ranked": False, "cost": 1, "description": "Ao conhecer alguém: rolagem imediata por informação"},
    # Skill-based
    {"name": "Artificer", "category": "skill", "ranked": False, "cost": 1, "description": "Cria itens com propriedades de poder via Expertise"},
    {"name": "Favored Foe", "category": "skill", "ranked": False, "cost": 1, "description": "+1d Decepção, Intimidação, Insight, Percepção vs tipo de inimigo"},
    {"name": "Improvised Tools", "category": "skill", "ranked": False, "cost": 1, "description": "Ignora penalidade de ferramentas ausentes"},
    {"name": "Startle", "category": "skill", "ranked": False, "cost": 1, "description": "Usa Intimidação para Feint em combate"},
    {"name": "Taunt", "category": "skill", "ranked": False, "cost": 1, "description": "Usa Decepção para Demoralize"},
    {"name": "Tracking", "category": "skill", "ranked": False, "cost": 1, "description": "Usa Percepção para rastreamento visual"},
]

# ────────────────────────────────────────────────────────────
# POWER LEVEL TABLE
# ────────────────────────────────────────────────────────────
POWER_LEVELS = [
    {"pl": 3, "pp": 45, "dp_cap": 3, "context": "Início de campanha; habilidades treinadas sem superpoderes"},
    {"pl": 5, "pp": 75, "dp_cap": 5, "context": "Agentes de elite, praticantes de magia, forças especiais"},
    {"pl": 7, "pp": 105, "dp_cap": 7, "context": "Super-humanos estabelecidos; campeões regionais"},
    {"pl": 10, "pp": 150, "dp_cap": 10, "context": "Padrão para campanhas de super-humanos experientes"},
    {"pl": 13, "pp": 195, "dp_cap": 13, "context": "Heróis icônicos; forças de escala planetária"},
    {"pl": 15, "pp": 225, "dp_cap": 15, "context": "Quase-divinos; entidades cósmicas menores"},
]

# ────────────────────────────────────────────────────────────
# AFFLICTION CONDITION OPTIONS (by degree)
# ────────────────────────────────────────────────────────────
AFFLICTION_CONDITIONS = {
    1: ["Dazed", "Entranced", "Fatigued", "Hindered", "Impaired", "Vulnerable"],
    2: ["Compelled", "Defenseless", "Disabled", "Exhausted", "Immobile", "Prone", "Stunned"],
    3: ["Asleep", "Controlled", "Incapacitated", "Paralyzed", "Transformed", "Unaware"],
}

# ────────────────────────────────────────────────────────────
# IMMUNITY OPTIONS
# ────────────────────────────────────────────────────────────
IMMUNITY_OPTIONS = [
    {"name": "Todos os efeitos de Fortitude", "cost": 30},
    {"name": "Tipo de dano específico (fogo, frio, elétrico, etc.)", "cost": 5},
    {"name": "Todo dano físico", "cost": 20},
    {"name": "Todo dano", "cost": 30},
    {"name": "Todos os efeitos de Willpower", "cost": 15},
    {"name": "Subtipo específico (veneno, doença, calor extremo, etc.)", "cost": 1},
    {"name": "Necessidade vital (fome, sede, sono — individual)", "cost": 1},
    {"name": "Todos os efeitos de um descritor completo", "cost": 20},
]

# ────────────────────────────────────────────────────────────
# DESCRIPTOR SUGGESTIONS
# ────────────────────────────────────────────────────────────
DESCRIPTOR_SUGGESTIONS = {
    "Origem": ["Mutante", "Treinado", "Tecnológico", "Divino", "Mágico", "Psiônico", "Alienígena", "Acidental", "Amaldiçoado"],
    "Elemento": ["Fogo", "Água", "Terra", "Ar", "Luz", "Sombra", "Elétrico", "Gravitacional", "Temporal", "Mental", "Vácuo", "Plasma"],
    "Resultado": ["Cegante", "Paralisante", "Corrosivo", "Regenerativo", "Ilusório", "Dimensional", "Letárgico", "Necrótico"],
    "Forma": ["Projétil", "Raio", "Onda", "Aura", "Campo", "Toque", "Área", "Linha", "Pulso", "Emanação", "Prisma"],
    "Escopo": ["Pessoal", "Alvo Único", "Grupo", "Área Definida", "Global", "Dimensional", "Temporal"],
}


# ────────────────────────────────────────────────────────────
# ENDPOINT — everything in one call
# ────────────────────────────────────────────────────────────
@router.get("/catalog")
async def get_system_catalog():
    """Return the complete system rules catalog as a single JSON payload."""
    return {
        "attributes": ATTRIBUTES,
        "attr_cost_table": ATTR_COST_TABLE,
        "skills": SKILLS,
        "effects": EFFECTS,
        "extras": EXTRAS,
        "flaws": FLAWS,
        "conditions": CONDITIONS,
        "advantages": ADVANTAGES,
        "power_levels": POWER_LEVELS,
        "affliction_conditions": AFFLICTION_CONDITIONS,
        "immunity_options": IMMUNITY_OPTIONS,
        "descriptor_suggestions": DESCRIPTOR_SUGGESTIONS,
    }
