"""initial schema

Revision ID: 876811a4c0d9
Revises: 
Create Date: 2026-03-27 23:53:27.051358
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876811a4c0d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('origin_descriptors', sa.Text(), nullable=False),
    sa.Column('power_level', sa.Integer(), nullable=False),
    sa.Column('pp_total', sa.Integer(), nullable=False),
    sa.Column('pp_spent', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('powers', sa.JSON(), nullable=False),
    sa.Column('advantages', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('complications', sa.JSON(), nullable=False),
    sa.Column('base_hq', sa.JSON(), nullable=True),
    sa.Column('vitalidade_max', sa.Integer(), nullable=False),
    sa.Column('vitalidade_current', sa.Integer(), nullable=False),
    sa.Column('ferimentos', sa.JSON(), nullable=False),
    sa.Column('hero_dice', sa.Integer(), nullable=False),
    sa.Column('active_conditions', sa.JSON(), nullable=False),
    sa.Column('dodge', sa.Integer(), nullable=False),
    sa.Column('parry', sa.Integer(), nullable=False),
    sa.Column('fortitude', sa.Integer(), nullable=False),
    sa.Column('willpower', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('gm_user_id', sa.Integer(), nullable=False),
    sa.Column('power_level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('optional_rules', sa.JSON(), nullable=False),
    sa.Column('combat_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gm_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_tables_code'), ['code'], unique=True)

    op.create_table('roll_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('character_name', sa.String(length=120), nullable=False),
    sa.Column('roll_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('pool_composition', sa.JSON(), nullable=False),
    sa.Column('dice_results', sa.JSON(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('complications', sa.Integer(), nullable=False),
    sa.Column('tn', sa.Integer(), nullable=True),
    sa.Column('margin', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['game_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roll_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roll_logs_table_id'), ['table_id'], unique=False)

    op.create_table('table_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['game_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_characters')
    with op.batch_alter_table('roll_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roll_logs_table_id'))

    op.drop_table('roll_logs')
    with op.batch_alter_table('game_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_tables_code'))

    op.drop_table('game_tables')
    op.drop_table('characters')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
